### ISSUE TITLE
Since 1.7.0 breaks forms without schema

### ISSUE THREAD

**Issue by datakurre** [plone/plone.autoform#20]
See comments at https://github.com/plone/plone.autoform/commit/6dd0af85a371805dcf4a69f0116d2a878f09db7b

E.g. many layout tiles defined in plone.app.standardtiles have no schema, but Mosaic still "creates" them through z3c.forms defined in plone.app.tiles.

**Comment by jensens** [comment]
This is fixed since 1.7.3 release with 0beaeb85057759aab310b496fce2be959be5e75c
