### ISSUE TITLE
Optimise performance of plone.autoform

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.autoform#4]
_Original author: optil...@gmail.com (March 04, 2009 02:52:12)_

The plone.autoform field ordering algorithms are used for the default display, edit and add forms. It 
does quite a lot of work in building up a form based on hints stored in the schema interface. This 
probably makes a default dexterity view fractionally slower than a standard page template used on 
an AT type (such as document_view).

It would be worth investigating whether this can be optimised, possibly using some internal 
caching.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=29_

**Comment by jensens** [comment]
outdated
